foos/urls.py
from django.conf.urls.defaults import *
from mysite.foos.models import *

info_dict = {
	'queryset': Team.objects.all(),
}

urlpatterns = patterns('mysite.foos.views',
	(r'^$', 'index'),
	(r'^leaderboard/$', 'leaderboard'),
	(r'^teams/$', 'team_list'),
	(r'^teams/(?P<team_id>\d+)/$', 'team_details'),
	(r'^games/$', 'games'),
)

urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	# Example:
	# (r'^mysite/', include('mysite.foo.urls')),

	# Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
	# to INSTALLED_APPS to enable admin documentation:
	# (r'^admin/doc/', include('django.contrib.admindocs.urls')),

	# Uncomment the next line to enable the admin:
	(r'^admin/', include(admin.site.urls)),

	(r'^foos/', include('mysite.foos.urls')),
)

foos/models.py
from django.db import models
from mysite.foos.models_views import *

class Player(models.Model):
	name = models.CharField(max_length=200)

class Team(models.Model):
	player1 = models.ForeignKey(Player, related_name='player1')
	player2 = models.ForeignKey(Player, related_name='player2')
	name = models.CharField(max_length=200)

	def get_wins(self):
		wins = Wins.objects.filter(pk=self.id)
		if len(wins) == 0:
			return 0L
		else:
			return wins[0].wins

class Game(models.Model):
	team1 = models.ForeignKey(Team, related_name='team1')
	team2 = models.ForeignKey(Team, related_name='team2')

class Score(models.Model):
	game = models.ForeignKey(Game)
	team = models.ForeignKey(Team)
	score = models.IntegerField()

foos/views.py
from django.template import *
from django.core.urlresolvers import *
from django.http import *
from django.shortcuts import *
from mysite.foos.models import *
from mysite.foos.models_views import *
from operator import itemgetter

def index(request):
	return render_to_response('foos/index.html')

def leaderboard(request):
	teams = Team.objects.all()
	d = dict()
	for team in teams:
		d[team.name] = team.get_wins()
	sorted_teams = list(reversed(sorted(d.items(), key=itemgetter(1))))
	return render_to_response('foos/leaderboard.html', {'teams': sorted_teams})

def team_list(request):
	teams = Team.objects.all()
	return render_to_response('foos/team_list.html', {'team_list': teams})

def team_details(request, team_id):
	team = Team.objects.get(pk=team_id)
	return render_to_response('foos/team_details.html', {'team': team})

def games(request):
	games = Game.objects.order_by('pk').reverse()
	return render_to_response('foos/games.html', {'games': games})

templates/foos/games.html
<h1>Games</h1>
{% for game in games %}
Game {{game.id}}
<br>
{% for score in game.score_set.all %}
Team: {{score.team_id}} Score: {{score.score}}
<br>
{% endfor %}
<br><br>
{% endfor %}

templates/foos/index.html
<h1>Foosball system</h1>
<ul>
	<li><a href="games">List of games</a></li>
	<li><a href="teams">List of teams</a></li>
	<li><a href="leaderboard">Leaderboard</a></li>
</ul>

templates/foos/leaderboard.html
<h1>Leaderboard</h1>
{% for i in teams %}
#{{forloop.counter}}
Team {{i.0}}
Wins {{i.1}}
<br>
{% endfor %}

templates/foos/team_details.html
<h1>{{team.name}}</h1>

<h3>Players</h3>
<ul>
	<li>{{team.player1.name}}</li>
	<li>{{team.player2.name}}</li>
</ul>

<h3>Games played</h3>

{# get score record for each game played by this team #}
{% for score in team.score_set.all %}
Game {{score.game_id}} <br>

{# for each game played by this team, get both scores #}
{% for scores in score.game.score_set.all %}
Team: {{scores.team_id}} Score: {{scores.score}}
<br>
{% endfor %}
<br><br>
{% endfor %}

templates/foos/team_list.html
{% if team_list %}
<h1>Teams</h1>
	<ul>
	{% for team in team_list %}
		<li><a href="/foos/teams/{{team.id}}/">{{team.name}}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No teams found.</p>
{% endif %}